In [2]:
import pandas as pd

Dataframe : table container

In [10]:

pd.DataFrame(
    {'Rooms':[1,2,1],'Bathrooms':[1,1,1],'Area':['Venice','Marseille','Paris'],'Price':[300,300,200]},
    index=['Solution 1','Solution 2','Solution 3']
)

            Rooms  Bathrooms       Area  Price
Solution 1      1          1     Venice    300
Solution 2      2          1  Marseille    300
Solution 3      1          1      Paris    200

In [9]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [13]:
quantities = ['4 cups', '1 cup', '2 large', '1 can']
items = ['Flour', 'Milk', 'Eggs', 'Spam']
recipe = pd.Series(quantities, index=items, name='Dinner')
recipe

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [8]:
wine_reviews = pd.read_csv("data/winemag-data_first150k.csv",index_col=0)
# to get dimension of the table
wine_reviews.shape
# to get 5 five rows
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

## Indexing

### iloc : integer location

```
Iloc uses standard python indexing so [0:10] will select entries from 0,...,9
```

In [27]:
data = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]},index=['X','Y','Z'])

selected_data = data.iloc[0:3, 0:2]
print(selected_data)

   A  B
X  1  4
Y  2  5
Z  3  6

### loc : select by dataframe label
```
Loc indexing different than standard python : [0,10] will select 0,...,10
```

In [28]:
selected_data = data.loc['X':'Z', 'A':'B']
print(selected_data)

   A  B
X  1  4
Y  2  5
Z  3  6

In [32]:
df = pd.DataFrame(
    {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Salary': [50000, 60000, 70000, 80000]})

max_salary = df.Salary.max()
f_salary = df.Salary[0]

print(max_salary)

80000

### Conditionnal selection

In [40]:
sample_reviews = wine_reviews.loc[[1,2,3,5,8]]

wine_reviews.loc[wine_reviews.country == 'Spain'].head()

wine_reviews.country =="Italy"

wine_reviews.loc[(wine_reviews.country == 'Italy') & (wine_reviews.points >= 90)].head()

wine_reviews.loc[wine_reviews.country.isin(['Italy', 'France'])].head()

wine_reviews.loc[wine_reviews.price.notnull()].head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [46]:
indices = [0,1,10,100]
features = ['country','price','region_1','region_2']
df = pd.DataFrame(wine_reviews.loc[indices,features])
df

    country  price     region_1     region_2
0        US  235.0  Napa Valley         Napa
1     Spain  110.0         Toro          NaN
10    Italy   80.0       Collio          NaN
100      US   24.0  South Coast  South Coast

In [50]:
top_oceania_wines = wine_reviews.loc[
    (wine_reviews.points >= 95) & 
    (wine_reviews.country.isin(['Australia','New Zealand']))
]
top_oceania_wines.head(3)

,country,description,designation,points,price,province,region_1,region_2,variety,winery,critic
2148,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Shiraz,Torbreck,everyone
2458,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Cabernet-Shiraz,Hickinbotham,everyone
3033,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Cabernet Sauvignon,Penfolds,everyone

### Assigning data

In [44]:
wine_reviews["critic"] = 'everyone'
wine_reviews["critic"]

0         everyone
1         everyone
2         everyone
3         everyone
4         everyone
            ...
150925    everyone
150926    everyone
150927    everyone
150928    everyone
150929    everyone
Name: critic, Length: 150930, dtype: object